# Currently, it is NOT possible to use PNP mode of Yarn Berry
# because of https://github.com/gohugoio/hugo/issues/8301
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
