baseURL = 'https://v2--blockchainetsociete.netlify.app/'
languageCode = 'fr-fr'
title = 'B&S'
theme = "custom-blist"


DefaultContentLanguage = "fr"
DefaultContentLanguageInSubdir = true

publishDir = "docs"
contentDir = "content"

[languages]
  [languages.fr]
    contentDir = "content/fr"
    weight = 1
    languageName = "Français"
    [languages.fr.params]
      introTitle = "Blockchain et Societe"
      introSubtitle = "Le site officiel de l'association crypto et blockchain"
      introPhoto = "/picture.jpg"
    
    [[languages.fr.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.fr.menu.main]]
        name = "Évènements"
        url = "events/"
        weight = 2
    
    [languages.fr.params.homepage.team]
        title = "Nos membres"

    [languages.fr.params.homepage.events]
        title = "Les derniers évènements"
        allBtn = "Tous les évènements"
        
    [languages.fr.params.homepage.posts]
        title = "Les derniers billets"
        
    [languages.fr.params.homepage.social]
        title = "Rejoignez-nous"
        description = "Échangez avec la communauté en direct, suivez nos actualités et inscrivez-vous à nos futurs évènements"
    
    [languages.fr.params.components.eventCard]
        infoBtn = "Plus d'info"

    [languages.fr.params.pages.events]
        title = "Les évènements"
        subtitle = "Retrouvez ici tous les évènements organisés par l'association Blockchain et Société depuis sa création en 2016."

[params]
  darkModeToggle = true
  
  # Enable search in header
  # enableSearch = true

  # Custom copyright - optional
  # copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-gray-100"


[params.social]
  twitter = "https://twitter.com/Blockchain44"
  slack = "https://join.slack.com/t/meetup-blockchain/shared_invite/zt-3u8hgq75-hkvVna9GdMnRwf7Pq4tqFw"
  github = "https://github.com/BlockchainEtSociete"
  meetup = "https://www.meetup.com/Blockchain-Societe-Nantes"
  youtube = "https://www.youtube.com/channel/UCLxvA3g5oqdItCMvO6Scfhg"
  email = "mailto:contact@blockchainsociete.org"
  facebook = "https://www.facebook.com/groups/822513524759506/"
  linkedin = "https://www.linkedin.com/company/blockchain-et-societe"