[build]
  publish = "docs"
  command = "HUGO_BASEURL=$URL yarn fetch-events && yarn build"

[build.environment]
  HUGO_VERSION = "0.91.2"
  NODE_VERSION = "16"
  NETLIFY_USE_YARN = "true"

[context.deploy-preview]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL yarn fetch-events && yarn build"

[context.branch-deploy]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL yarn fetch-events && yarn build --buildDrafts --buildFuture"
