name: Scheduled Netlify deploy

on:
  schedule:
    - cron: "17 6 * * MON,WED,SAT"

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Trigger hook
        run: curl -d '' https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_HOOK_ID }}

  keepalive:
    name: Keep Alive workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master
        with:
          commit_message: keep alive Netlify workflow auto-commit
          committer_username: blockchainetsocietebot
          committer_email: services@blockchainsociete.org
